### ISSUE TITLE
Coordinate with ExpandingMan

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/FeatherLib.jl#1]
@ExpandingMan: I took a crack at what it would take to use your Arrow.jl and feather work for [FeatherFiles.jl](https://github.com/davidanthoff/FeatherFiles.jl). This repo is what I ended up with.

The basic story is that I took your ``arrow1`` branch from Feather.jl, removed all the DataStreams.jl integration and turned it into this repo here. So this is a repo that provides feather read and write features, but has no dependency on either the DataStreams.jl or the [TableTraits.jl](https://github.com/davidanthoff/TableTraits.jl) packages. I then provide the [TableTraits.jl](https://github.com/davidanthoff/TableTraits.jl) integration in https://github.com/davidanthoff/FeatherFiles.jl/pull/3.

I'm *really* excited about this: the design finally allows a scenario where one has a super large feather file, and then queries that with [Query.jl](https://github.com/davidanthoff/Query.jl) in a fully streaming fashion. So something like ``load("foo.feather") |> filter(_.a>3) |> save("output.csv")`` is now completely streaming and should actually work with data sets that don't fit into main memory (in theory, I haven't tried it). One can obviously add arbitrarily many additional query operations into this pipeline. I've also added support for a new interface that is defined in [TableTraits.jl](https://github.com/davidanthoff/TableTraits.jl) that should make it fairly easy to materialize things quickly into a tabular structure. Currently none of the TableTraits.jl sinks support this new interface, so they always will use the iterable tables interface instead, but I hope to add support to some soon, and then we should see big speedups. That new interface is described [here](http://www.david-anthoff.com/jl4ds/latest/tabletraits.html) as the columns-view interface.

It would of course now be nice if we can avoid too many forks etc. Do you think it would make sense that Feather.jl could reuse the code here in FeatherLib.jl, in the same way that FeatherFiles.jl uses the code here? I do believe that the way FeatherLib.jl is structured right now should make that pretty straightforward. I'll leave that up to you, but it would be kind of nice, I think.

From my end it would be great if you would register Arrow.jl rather sooner than later, then I could release a version of FeatherFiles.jl that uses all of that.

Finally, given that the work here in FeatherLib.jl is really mostly yours and not mine, I would happily transfer this repo over to your account, if you would prefer that.

**Comment by ExpandingMan** [comment]
Cool!  I'm also very excited to see what Query.jl will be able to do with this!  That's very much the sort of thing I had in mind when I took the time to write Arrow.jl.  In the past I remember having performance issues with "large" datasets using Query, but I certainly didn't carefully look into it and I'm sure it's something that's solvable if it isn't already.  We can discuss that over there when and if the issue comes up.

I very much had in mind Feather being a "replacement for databases" in many situations and I was always very drawn to it because it is dead simple compared to e.g. Parquet or Postgres and nevertheless provides about 99% of the functionality I need 90% of the time (at least in principle, I had to write some of it!).

I would like to try to persuade you one last time to try to use Feather.jl as the base for all things feather.  Despite the use of the names `Source` and `Sink`, the *only* part of DataStreams that is really integral to the functioning of my PR of Feather.jl is `Data.Schema` (as I'm sure you've noticed by now).  I'm sure you've also noted that `Data.Schema` provides a lot of functionality which is badly needed for Feather.  I was being a bit lazy and wrote a `write` method that uses `Data.stream!` but this could easily be changed (in fact it might get *slightly* better performance if it only uses Arrow).  The reamaining DataStreams code, as I'm sure you have seen, is extremely minimal, and doesn't even get called unless you use DataStreams directly.  Additionally, the only major churn that occurred with DataStreams was the recent overhaul.  The main reason I keep trying to convince you of this is that I really see Feather.jl and FeatherFiles.jl as being basically the *only* two uses of FeatherLib.jl, so it just seems a little silly to me to separate into so many tiny packages, especially as the languages has a compile caching issue with interdependent packages.

If I still haven't convinced you, I would of course much prefer to base Feather.jl on FeatherLib.jl than have them as completely standalone packages.  So if you decide you need to go that route I'll try to re-do the Feather.jl PR by the end of next week.

I'm perfectly happy for this repo to be on your account.  In fact, by the time we get Arrow.jl tagged and announced I'd like to add you as an admin, assuming you are interested.  In my current role as a data scientist this kind of tooling is definitely a secondary concern, I just often find myself thinking "wouldn't it be nice".  So, it's safe to assume that there will be a time in the not-so-distant future where I simply won't have the time to deal with Arrow or Feather very much, and my open source contributions will more likely go to things like JuMP, Flux, Optim or POMPDPs.  (And I still very much want to take the time to do a lattice gauge theory package, which is a big project!)

Anyway, for Arrow.jl: I'm going to add more unit tests before the end of next week (March 26) and when they are a little less embarrassing I will tag it, register it, and add you as an admin.  If it's not done by then, please get on there and complain!

**Comment by davidanthoff** [comment]
The reason I don't want to take a dependency on DataStreams.jl is that it ties everything to DataFrames v0.11 and newer and makes it impossible to support DataFrames v0.10. The whole Queryverse right now *does* support both DataFrames v0.10 and v0.11, and I can't drop that.

I think there is a larger lesson in that: I think we are all better off if we don't tie the versions of the Queryverse and the DataStreams world too tightly together. If we did, every breaking change in one of them necessitates compat work in the other world, and at least from my end that is just not manageable. I will continue to fully interop with the DataStreams world, but ideally I'd like that to happen only in IterableTables.jl, i.e. at one point, but have packages like FeatherFiles.jl not tied to breaking changes in the DataStreams.jl world.

**Comment by ExpandingMan** [comment]
I don't really understand why you would support DataFrames v0.10.  If you really wanted to use `NullableArray`, the great virtue of DataFrames v0.11 is that it makes it very easy for you to still do that: it is completely agnostic about what types of `AbstractVector` it uses as columns.  Furthermore v0.10 will never be updated for Julia 0.7 (unless you do it yourself).  I also thought that you already had lots of dependencies on DataStreams since you clearly make use of it, so I still don't think I see the harm of having it in Feather, *especially* if we take steps to make sure you don't have to use `Data.stream!` or `Data.streamfrom` or anything like that.  I had deliberately designed it so that you wouldn't have to do that and all you'd need is `Data.Schema` which is very useful for Feather.

I'm not going to fight you over it though, so I'm going to update FeatherLib.jl, close my existing PR to Feather.jl and create a new one with FeatherLib.jl as a dependency.  I *would* like to hear from @quinnj however to say whether he would indeed be interested in merging a PR with FeatherLib to Feather before I do this however.

**Comment by quinnj** [comment]
Can we not keep bifurcating every package? Please? I just don't understand how any of this is good for end users. Let's put ourselves in the place of a new user who hears about julia and wants to try out some data processing tasks:

* oh, CSV.jl, great, I can read csv files. Oh wait, what's CSVFiles.jl? TextParse.jl? uCSV.jl? Oh dear....
* Guess I'll try my feather file. Ah, Feather.jl! Oh wait, there's FeatherFiles.jl.....oh, and FeatherLib.jl.......

It's just sad to me that the julia data ecosystem is devolving into a state that is overall worse for end users because package developers can't take the time to collaborate and work together. I'm more than happy to merge @ExpandingMan's great work on Arrow.jl into Feather.jl. It's a fairly large changeset, so it's not something I can review in a night, but I've been following the work closely and have looked over things here and there. I think we could easily merge the necessary changes there in the next week (and get the Arrow.jl package registered). 

I'm against creating yet another pseudo-package that will just confuse end users. Please @davidanthoff, let's collaborate and not make things more confusing.

**Comment by davidanthoff** [comment]
> I don't really understand why you would support DataFrames v0.10.

We have many person-years of internal code that is based on v0.10 and I need to support that. There are also still lots of other packages that haven't made the moved, and I want to support folks that are using  those as well.

>  If you really wanted to use ``NullableArray``

This has nothing to do with ``NullableArray``. [DataTables.jl](https://github.com/JuliaData/DataTables.jl) was the version that used ``NullableArray``, that is a completely separate story. Just for the record, I don't think (and never did) that ``NullableArray`` as it was implemented was a good option for the data stack.

> I also thought that you already had lots of dependencies on DataStreams since you clearly make use of it in IterableTables.jl

I go through great pains to support both the DataFrames v0.10 and v0.11 world simultaneously in IterableTables.jl. But there is no hard dependency in terms of anything in a REQUIRE file.

So just to be super clear: I have absolutely nothing against DataStreams.jl or Feather.jl in general. Quite the opposite, I think both are great packages! But they would impose dependency restrictions on the Queryverse that I don't want take on at this point.

@quinnj It is not clear to me what you are concretely proposing. That we merge Feather.jl and FeatherFiles.jl into Feather.jl? That would require that Feather.jl takes on dependencies on TableTraits.jl, DataValues.jl etc. And I need something that keeps supporting DataFrames v0.10 for quite a bit longer, so that would also be a requirement. We could certainly think that option through and try to figure out whether that makes sense or not. My best guess is that it isn't, but I might well be wrong. Is that what you have in mind?

The idea for FeatherLib.jl was really about collaborating and making sure we can share code between the DataStreams world and the Queryverse. I just had assumed (maybe prematurely?) that you wouldn't want to take on all these dependencies for Feather.jl and that the best strategy would be to find a way to share code under the assumption that both Feather.jl and FeatherFiles.jl are around. In that case it seemed easiest to factor the common code out into a package that both these packages could depend on.

I think my first priority at this point would be to not hold the great work that @ExpandingMan has done up. I think we all agree that Arrow.jl really can just be registered as soon as possible, right? If both @ExpandingMan and @quinnj would prefer that Feather.jl doesn't depend on something like FeatherLib.jl, I think you should just go ahead and merge the PR in Feather.jl and get this stuff out. I would most likely just copy the code in this repo here over into FeatherFiles.jl in the short term then (having a FeatherLib.jl that is only used by FeatherFiles.jl even to me seems silly ;). I'm done with the whole integration into the TableTraits.jl/Query.jl world and am keen to get this stuff out. And then we could still figure out longer term whether there is a way to merge Feather.jl and FeatherFiles.jl.

**Comment by nalimilan** [comment]
DataFrames 0.10 will never support Julia 0.7, so it's going to disappear soon anyway. What will happen to FeatherLib then?

**Comment by ExpandingMan** [comment]
> This has nothing to do with NullableArray

Oh sorry, I was getting them confused, the old DataFrames.jl was the one that used DataArrays.  Ok, at least I understand now what the issue would be with using Feather.jl its the prospect of a DataFrames dependency.  By the way, I was already contemplating removing that, but I would need DataStreams to do that, and since I'm not too sure that DataStreams will support my 3 different types of `getindex` semantics using only `Data.streamfrom` I'm not sure that will work.

I have to say though I still can't fathom what it is about DataFrames v0.10 that's worth saving.  Weren't DataArrays pretty much the worst case scenario as far as type stability goes?  And again, as I keep emphasizing, my very favorite thing about DataFrames v0.11 is how agnostic it is about the underlying column types.  So you could make something very close to DataFrames v0.10 just by using DataArrays in DataFrames v0.11.  I know that you have your reservations about `Union` types, and I have been following the NamedTuples thread on discourse and I agree that there are serious concerns about this as a long term solution, but DataFrames v0.11 doesn't really care about `missing`.  All it has are a few utility functions for converting column types, but you don't need to use them.  So, I have read all your arguments but I have to admit to still being totally baffled why you'd want to hold on to v0.10.  As @nalimilan pointed out, you will soon have to split it into a new repo and update it for 0.7, and I really can't understand why you'd want to do that when it has been done for v0.11 already (by me, incidentally).

**Comment by davidanthoff** [comment]
> DataFrames 0.10 will never support Julia 0.7, so it's going to disappear soon anyway. What will happen to FeatherLib then?

Nothing? FeatherLib.jl doesn't have a dependency on either DataFrames.jl version, so it is decoupled from that whole question. I believe it should more or less support julia 0.6 and 0.7 at the moment already. Or did I misunderstand the question and you were getting at something else?

I certainly don't expect DataFrames v0.10 to be ported to julia 0.7, just in case I gave a wrong impression on that.

> I have to say though I still can't fathom what it is about DataFrames v0.10 that's worth saving.

Nothing from a technical point of view, in my mind. But we have budget constraints, deadlines and various other constraints on our internal projects, and porting them all over to v0.11 at this point is just not in the cards. If I had an unlimited budget, no deadlines etc., sure, we'd just port everything.

So what I'd like to have is a version of FeatherFiles.jl that makes use of the cool work in Arrow.jl, that is compatible with DataFrames v0.10 and runs on julia 0.6. That is what we need for our internal stuff right now. FeatherLib.jl and a new branch in FeatherFiles.jl delivers on all that (and of course also works with DataFrames v0.11). And both Arrow.jl and FeatherLib.jl do work on julia 0.7, I believe (or should with minimal tweaks), so nothing in that would prevent a library that depends on FeatherLib.jl to move to julia 0.7 at any point. If all of that is not compatible with the plans for Feather.jl, I can completely understand. I certainly don't want to make the life of the folks that maintain that package more complicated than necessary, and in that case I would suggest you just merge the PR in Feather.jl, and I use the code here in FeatherFiles.jl. That would imply a certain amount (but not a huge amount) of code duplication, and from my point of view I would prefer to avoid that and collaborate on the shared parts of the code, but I can certainly live with either option.

> I know that you have your reservations about Union types, and I have been following the NamedTuples thread on discourse and I agree that there are serious concerns about this as a long term solution,

While that is true, this is another issue that has nothing to do with my argument here :) If DataFrames.jl had used Bliss.jl as the solution for missing values (where Bliss.jl is a fictitious solution that solves all problems around missing values) I would still want to support v0.10 for a while to accommodate folks that have legacy code basis (like my own group). The issue is that DataFrames.jl v0.11 was a breaking release, not what the new missing data value story is.

**Comment by ExpandingMan** [comment]
> While that is true, this is another issue that has nothing to do with my argument here :)

That's how it initially seemed to me, but when I made my comment about `missing` I was still trying to figure out what it was that you objected to about v0.11.

**Comment by nalimilan** [comment]
> Nothing? FeatherLib.jl doesn't have a dependency on either DataFrames.jl version, so it is decoupled from that whole question. I believe it should more or less support julia 0.6 and 0.7 at the moment already. Or did I misunderstand the question and you were getting at something else?

Actually my question was: what will be the point of having two Feather packages once there is no need to work with DataFrames 0.10?

**Comment by davidanthoff** [comment]
> Actually my question was: what will be the point of having two Feather packages once there is no need to work with DataFrames 0.10?

I've assumed that you guys are not game to add native TableTraits.jl/iterable tables integration to the packages that you maintain, mostly based on the reaction to https://github.com/JuliaData/DataFrames.jl/pull/1215 and https://github.com/JuliaDatabases/MySQL.jl/issues/88. I do want a native feather story for the Queryverse that uses the table interop story of that ecosystem, and so FeatherFiles.jl exists. I also have a pretty specific idea how I'd like tabular file IO to look like and interact with the other packages in the Queryverse from an end-user point of view. I didn't think it would be appropriate to storm into the existing packages and suggest to change everything, when they work perfectly well for a lot of scenarios. In general I think it is a good idea to try out multiple approaches to the same problem and just see what works and resonates with folks.

**Comment by nalimilan** [comment]
We need a common basic abstraction for tables which does not depend on `DataValue`, then we won't have to duplicate all packages. Do you only need the features from TableTraits, or is IterableTables also a dependency? Is there a reason why there couldn't be a generic fallback for all tables that implement the DataStreams interface?
